{
 "title": "sample-service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Application Load (Requests/Min)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(app_request_count_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Total requests count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_request_count_total" }
   ]
  }
 ]
}