global:
    scrape_interval: 30s
    evaluation_interval: 1m

scrape_configs:
    - job_name: sample-service
      metrics_path: /prometheus

      dns_sd_configs:
      - names:
        - sample-service-service-discovery-service.sample-service.noname.local
    


