global:
    scrape_interval: 30s
    evaluation_interval: 30s

rule_files:
    - rules/alerting_rules.yml

scrape_configs:
    - job_name: sample-service
      metrics_path: /metrics

      dns_sd_configs:
        - names:
            - sample-service-service-discovery-service.sample-service.noname.local

alerting:
    alertmanagers:
        - dns_sd_configs:
            - names:
                - alertmanager-service-discovery-service.alertmanager.noname.local