receivers:
    - name: slack-notifications
      slack_configs:
        - channel: '#ymcne2019-alerts'
          api_url: https://hooks.slack.com/services/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


route:
    group_by: ['alertname']
    group_interval: 30s
    repeat_interval: 30m
    group_wait: 1m
    receiver: slack-notifications